model:
  checkpoint: /home/test/wsk/19RC-SBDD/external/SBDD-benchmarking/retrained_ckpts/Pocket2Mol.pt
sample:
  seed: 2036
  num_samples: 128
  beam_size: 128
  max_steps: 60
  threshold:
    focal_threshold: 0.5
    pos_threshold: 0.25
    element_threshold: 0.3
    hasatom_threshold: 0.6
    bond_threshold: 0.4
